### ISSUE TITLE
How to use without webpack

### ISSUE THREAD

**Issue by Ethan-Arrowood** [NeekSandhu/monaco-editor-textmate#21]
In this project readme you state it is recommended to use this webpack plugin to disable the included language things.

> you're advised to use Webpack with monaco-editor-webpack-plugin which allows you to control which of "built-in" languages should monaco-editor use/bundle, leaving the rest.

But what if I'm not using webpack? Is there a way to do this using the monaco api? Even if its messy/ requires some async grossness?

**Comment by NeekSandhu** [comment]
Are you using any bundler at all?

**Comment by QuevedoIB** [comment]
Hi, I'm using Vite and I would like to know if it's possible to make this package work without webpack. (No bundler)

**Comment by NeekSandhu** [comment]
Unfortunately, I do not have any experience with any of those tools, so I can't really point you in a straight direction. I can advise on hacking by using resolve aliases. Find out what paths monaco tries to "require" when it attempts to bundle the languages, and then monkey patch those paths gracefully using aliases through a relevant config option provided by your bundler.

**Comment by QuevedoIB** [comment]
Since I couldn't manage to hack with aliases I installed monaco-editor-core which comes without monaco-languages that causes the problem WebPack pluggin tries to patch. 

My theming is now working but since I've lost all the languages default configuration (completionProviders,etc) there's no suggestions when typing. I'd like to know if there's some way to set the default configs back when theming is all set up. I believe that with the example in this repo happens the same (since default languages aren't loaded).
